=== Veiasai/O-Log/rdkafka/conf/cppStream.xsd
<?xml version="1.0"?>

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.optiver.com.au/cppStream"
    xmlns="http://www.optiver.com.au/cppStream"
    elementFormDefault="qualified">

<xs:element name="confEntry">
    <xs:complexType>
        <xs:element name="entryKey" type="xs:string" \>
        <xs:element name="entryValue" type="xs:string" \>
    </xs:complexType>
</xs:element>

<xs:element name="consumer">
    <xs:complexType>
        <xs:element name="topic_list">
            <xs:element name="topic" type="xs:string" maxOccurs="unbounded" minOccurs="1"\>
        </xs:element>
        <xs:element name="global_conf">
            <confEntry maxOccurs="unbounded" \>
        </xs:element>
        <xs:element name="topic_conf">
            <confEntry maxOccurs="unbounded" \>
        </xs:element>
    </xs:complexType>
</xs:element>

<xs:element name="producer">
    <xs:complexType>
        <xs:element name="topic_list">
            <xs:element name="topic" type="xs:string" maxOccurs="1" minOccurs="1"\>
        </xs:element>
        <xs:element name="global_conf">
            <confEntry maxOccurs="unbounded" \>
        </xs:element>
        <xs:element name="topic_conf">
            <confEntry maxOccurs="unbounded" \>
        </xs:element>
    </xs:complexType>
</xs:element>

<xs:element name="cppStream">
    <xs:complexType>
        <xs:element name = "consumers">
            <consumer maxOccurs="unbounded" minOccurs="1">
        </xs:element>
        <xs:element name = "producers">
            <producer maxOccurs="unbounded" minOccurs="1">
        <xs:element name = "producers">
    </xs:complexType>
</xs:element>

</xs:schema>

=== Veiasai/O-Log/rdkafka/conf/cppStream.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cppStream
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cppStream.xsd">
    <comsumers>
        <comsumer>
            <topic_list>
                <topic>fluent-newData</topic>
            </topic_list>
            <global_conf>
                <confEntry>
                    <entryKey>group.id</entryKey>
                    <entryValue>test_group_id</entryValue>
                </confEntry>
                <confEntry>
                    <entryKey>metadata.broker.list</entryKey>
                    <entryValue>kafka:9092</entryValue>
                </confEntry>
            </global_conf>
        </comsumer>
    </comsumers>
    <producers>
        <producer>
            <topic_list>
                <topic>rdkafkaPtest</topic>
            </topic_list>
            <global_conf>
                <confEntry>
                    <entryKey>metadata.broker.list</entryKey>
                    <entryValue>kafka:9092</entryValue>
                </confEntry>
            </global_conf>
        </producer>
    </producers>
</cppStream>

=== Veiasai/O-Log/rdkafka/cppStream.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cppStream
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cppStream.xsd">
    <comsumer>
        <topic>fluent-newData</topic>
        <confEntry>
            <entryKey>group.id</entryKey>
            <entryValue>test_group_id</entryValue>
        </confEntry>
        <confEntry>
            <entryKey>metadata.broker.list</entryKey>
            <entryValue>kafka:9092</entryValue>
        </confEntry>
    </comsumer>
    <producer>
        <topic>rdkafkaPtest</topic>
        <confEntry>
            <entryKey>metadata.broker.list</entryKey>
            <entryValue>kafka:9092</entryValue>
        </confEntry>
    </producer>
</cppStream>
