=== Veiasai/O-Log/Conveyor/conf/conveyor.xsd
<?xml version="1.0"?>

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.optiver.com.au/conveyor"
    xmlns="http://www.optiver.com.au/conveyor"
    elementFormDefault="qualified">

<xs:element name="filter">
    <xs:complexType>
        <xs:element name="filterType" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="filterRule" type="xs:string" maxOccurs="1" minOccurs="1"/>
    </xs:complexType>
</xs:element>

<xs:element name="worker">
    <xs:complexType>
        <xs:element name="filePath" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="brokers" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="topic" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="backupType" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="filters">
            <filter maxOccurs="unbounded" minOccurs="1"/>
        </xs:element>
    </xs:complexType>
</xs:element>

<xs:element name="group">
    <worker maxOccurs="unbounded" minOccurs="1"/>
</xs:element>

<xs:element name="conveyor">
    <xs:complexType>
        <xs:element name="hostId" type="xs:string" maxOccurs="1" minOccurs="1"/>
        <xs:element name="quotas">
            <xs:element name="quota" type="xs:integer" maxOccurs="unbounded" minOccurs="1"/>
        </xs:element>
        <xs:element name="groups">
            <group maxOccurs="unbounded" minOccurs="1"/>
        </xs:element>
    </xs:complexType>
</xs:element>

</xs:schema>

=== Veiasai/O-Log/Conveyor/conf/conveyor.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<conveyor
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="conveyor.xsd">
    <hostId>opdlvm0001</hostId>
    <quotas>
        <quota>1024*1024*2</quota>
        <quota>1024*1024*4</quota>
    </quotas>
    <groups>
        <group>
            <worker>
                <filePath>/olog/src/github.com/veiasai/olog/PythonScript/DataDir/rb1000.log</filePath>
                <brokers>kafka:9092</brokers>
                <topic>rb1000</topic>
                <backupType>disk</backupType>
                <filters>
                    <filter>
                        <!-- <filterType>empty</filterType> -->
                        <filterType>regex</filterType>
                        <filterRule>^[0-9]{13} \[Info  \] \[DATA_RECORDER\]*</filterRule>
                    </filter>
                </filters>
            </worker>
            <worker>
                <filePath>/olog/src/github.com/veiasai/olog/PythonScript/DataDir/rb1001.log</filePath>
                <brokers>kafka:9092</brokers>
                <topic>rb1001</topic>
                <backupType>disk</backupType>
                <filters>
                    <filter>
                        <filterType>empty</filterType>
                        <!-- <filterType>regex</filterType>
                        <filterRule>^[0-9]{13} \[Info  \] \[DATA_RECORDER\]</filterRule> -->
                    </filter>
                </filters>
            </worker>
        </group>
        <group>
            <worker>
                <filePath>/olog/src/github.com/veiasai/olog/PythonScript/DataDir/rb1002.log</filePath>
                <brokers>kafka:9092</brokers>
                <topic>rb1002</topic>
                <backupType>disk</backupType>
                <filters>
                    <filter>
                        <filterType>empty</filterType>
                        <!-- <filterType>regex</filterType>
                        <filterRule>^[0-9]{13} \[Info  \] \[DATA_RECORDER\]</filterRule> -->
                    </filter>
                </filters>
            </worker>
            <worker>
                <filePath>/olog/src/github.com/veiasai/olog/PythonScript/DataDir/rb1003.log</filePath>
                <brokers>kafka:9092</brokers>
                <topic>rb1003</topic>
                <backupType>online</backupType>
                <filters>
                    <filter>
                        <filterType>empty</filterType>
                        <!-- <filterType>regex</filterType>
                        <filterRule>^[0-9]{13} \[Info  \] \[DATA_RECORDER\]</filterRule> -->
                    </filter>
                </filters>
            </worker>
        </group>
    </groups>
</conveyor>
